import * as cheerio from "cheerio";
import seurakuntaData from "./data/seurakunnat.json" with { type: "json" };

export interface Vuosivali {
  alku: number;
  loppu: number;
}

/** Parses Hiski year coverage text such as "1848, 1854-1856" into ranges. */
export function parseVuosivalit(teksti: string): Vuosivali[] {
  return teksti
    .split(",")
    .map((osa) => osa.replace(/\s+/g, ""))
    .filter((osa) => osa.length > 0)
    .map((osa) => {
      const [alku, loppu = alku] = osa.split("-").map(Number);
      return { alku: alku!, loppu: loppu! };
    });
}

export const KIRJAT = ["kastetut", "vihityt", "haudatut", "smuutt", "umuutt"] as const;
export type Kirja = (typeof KIRJAT)[number];

export interface Seurakunta {
  koodi: string;
  nimi: string;
  rinnakkaisnimi?: string;
  koko_nimi: string;
  vuodet: Record<Kirja, Vuosivali[]>;
}

/** All Hiski parishes, generated by scripts/paivita-seurakunnat.ts. */
export const SEURAKUNNAT: readonly Seurakunta[] = seurakuntaData;

const KOODI_LINKISTA = /^\/hiski\?fi\+(\d{4})$/;

/**
 * Parses the book list Hiski returns when every parish is selected at once.
 * Each row holds the full parish name and the indexed years per book.
 */
export function parseSeurakuntaluettelo(html: string): Seurakunta[] {
  const $ = cheerio.load(html);
  const tulos: Seurakunta[] = [];
  $("tr").each((_, rivi) => {
    const solut = $(rivi).children("td");
    const linkki = solut.first().find("a");
    const koodi = KOODI_LINKISTA.exec(linkki.attr("href") ?? "")?.[1];
    if (!koodi) return;
    const koko_nimi = linkki.text().trim();
    const erotin = koko_nimi.indexOf(" - ");
    const vuodet = Object.fromEntries(
      KIRJAT.map((kirja, i) => [kirja, parseVuosivalit(solut.eq(i + 1).text())]),
    ) as Record<Kirja, Vuosivali[]>;
    tulos.push({
      koodi,
      nimi: erotin >= 0 ? koko_nimi.slice(0, erotin) : koko_nimi,
      ...(erotin >= 0 && { rinnakkaisnimi: koko_nimi.slice(erotin + 3) }),
      koko_nimi,
      vuodet,
    });
  });
  return tulos;
}

/** Lowercases, strips diacritics (ä→a, ö→o, å→a) and collapses whitespace. */
export function normalisoi(s: string): string {
  return s
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

/** How well a parish matches a query; lower is better. */
enum Taso {
  Koodi,
  Tasmaa,
  Alkaa,
  SananAlku,
  Sisaltaa,
  Vartalo,
}

interface Osuma {
  seurakunta: Seurakunta;
  taso: Taso;
  /** Orders stem matches: how far the closest name words are from the query. */
  etaisyys: number;
}

const sanat = (s: string) => s.split(/[^\p{L}\p{N}]+/u).filter(Boolean);

const yhteinenAlku = (a: string, b: string) => {
  let i = 0;
  while (i < a.length && i < b.length && a[i] === b[i]) i++;
  return i;
};

/**
 * Finnish parish names are often in the genitive ("Turun", "Kristiinankaupungin"),
 * so a query word matches a name word when they share most of their beginning.
 */
const vartaloTasmaa = (hakusana: string, nimisana: string) =>
  yhteinenAlku(hakusana, nimisana) >= Math.max(3, hakusana.length - 3);

/** Smaller when name words share a longer beginning and a similar length. */
function vartaloEtaisyys(hakusanat: string[], nimisanat: string[]): number {
  let summa = 0;
  for (const h of hakusanat) {
    summa += Math.min(
      ...nimisanat.map((n) => h.length - yhteinenAlku(h, n) + Math.abs(h.length - n.length)),
    );
  }
  return summa;
}

type Luokitus = Pick<Osuma, "taso" | "etaisyys">;

function luokittele(haku: string, seurakunta: Seurakunta): Luokitus | undefined {
  const taso = (t: Taso): Luokitus => ({ taso: t, etaisyys: 0 });
  if (/^\d{1,4}$/.test(haku)) {
    return haku.padStart(4, "0") === seurakunta.koodi ? taso(Taso.Koodi) : undefined;
  }
  const nimet = [seurakunta.nimi, seurakunta.rinnakkaisnimi, seurakunta.koko_nimi]
    .filter((n): n is string => n !== undefined)
    .map(normalisoi);
  if (nimet.some((n) => n === haku)) return taso(Taso.Tasmaa);
  if (nimet.some((n) => n.startsWith(haku))) return taso(Taso.Alkaa);
  const nimisanat = sanat(nimet.join(" "));
  const hakusanat = sanat(haku);
  if (hakusanat.length === 0) return undefined;
  if (hakusanat.every((h) => nimisanat.some((n) => n.startsWith(h)))) return taso(Taso.SananAlku);
  if (nimet.some((n) => n.includes(haku))) return taso(Taso.Sisaltaa);
  if (hakusanat.every((h) => nimisanat.some((n) => vartaloTasmaa(h, n)))) {
    return { taso: Taso.Vartalo, etaisyys: vartaloEtaisyys(hakusanat, nimisanat) };
  }
  return undefined;
}

function etsiOsumat(haku: string, lista: readonly Seurakunta[]): Osuma[] {
  const normalisoitu = normalisoi(haku);
  if (!normalisoitu) return [];
  const osumat = lista
    .flatMap((seurakunta) => {
      const luokitus = luokittele(normalisoitu, seurakunta);
      return luokitus ? [{ seurakunta, ...luokitus }] : [];
    });
  // Loose stem matches are only useful when nothing better was found.
  const parempia = osumat.some((o) => o.taso < Taso.Vartalo);
  return osumat
    .filter((o) => !parempia || o.taso < Taso.Vartalo)
    .sort(
      (a, b) =>
        a.taso - b.taso ||
        a.etaisyys - b.etaisyys ||
        a.seurakunta.nimi.localeCompare(b.seurakunta.nimi, "fi"),
    );
}

/** Finds parishes by code, name or parallel name, best matches first. */
export function etsiSeurakunta(
  haku: string,
  lista: readonly Seurakunta[] = SEURAKUNNAT,
): Seurakunta[] {
  return etsiOsumat(haku, lista).map((o) => o.seurakunta);
}

const MAX_EHDOKKAITA = 10;

/** A parish name that did not resolve to exactly one parish. */
export class SeurakuntaVirhe extends Error {
  constructor(
    readonly syote: string,
    readonly ehdokkaat: Seurakunta[],
  ) {
    super(
      ehdokkaat.length === 0
        ? `Seurakuntaa "${syote}" ei löytynyt.`
        : `Seurakunta "${syote}" ei ole yksiselitteinen. Ehdokkaat: ${ehdokkaat
            .map((s) => `${s.koodi} ${s.koko_nimi}`)
            .join("; ")}`,
    );
    this.name = "SeurakuntaVirhe";
  }
}

function ratkaiseYksi(syote: string): Seurakunta {
  const osumat = etsiOsumat(syote, SEURAKUNNAT);
  const tarkat = osumat.filter((o) => o.taso <= Taso.Tasmaa);
  if (tarkat.length === 1) return tarkat[0]!.seurakunta;
  // A lone stem match is only a guess, so it is offered as a candidate instead.
  if (tarkat.length === 0 && osumat.length === 1 && osumat[0]!.taso < Taso.Vartalo) {
    return osumat[0]!.seurakunta;
  }
  throw new SeurakuntaVirhe(
    syote,
    osumat.slice(0, MAX_EHDOKKAITA).map((o) => o.seurakunta),
  );
}

/**
 * Resolves parish codes or names to parishes, dropping duplicates.
 * Throws SeurakuntaVirhe for an unknown or ambiguous entry.
 */
export function ratkaiseSeurakunnat(syotteet: readonly string[]): Seurakunta[] {
  const tulos = new Map<string, Seurakunta>();
  for (const syote of syotteet) {
    const seurakunta = ratkaiseYksi(syote);
    tulos.set(seurakunta.koodi, seurakunta);
  }
  return [...tulos.values()];
}
